apostrophecms/apostrophe-workflow

public/css/menu.less, public/css/user.less, views/export-modal.html, views/locale-tree.html
A couple things:
1. Is this the best way to highlight this item? Maybe a checkmark icon to the right of the locale name would also be good.
2. This should probably be refactored into a macro. Note if you agree.
3. I also placed the text inside the label tag so it's clickable.
Here's the current appearance with this PR:
For reference Michelin ticket: https://git.dgadteamdev.com/pa/apostrophe-enhancements/issues/72
=> First pass at highlighting the current locale

lib/modules/apostrophe-workflow-pages/public/js/editor.js
Note: I didn't need to add notification feedback to the 'submit' selection, because clicking that from the workflow dialog immediately closes the modal. The difference is that when you click on 'commit' you get a secondary modal where you can "Cancel." This feedback clarifies the fact that the page has already been created and saved, and therefore when you click "Cancel" on this secondary modal you are only cancelling the commit action and not the page creation.
=> Added a notification feedback to the user

lib/implementation.js
When there are too many documents in database, the aggregate to find duplicate documents fails. The option `allowDiskUse: true` handles this case.
=> Handle workflowGuid index with many documents

lib/routes.js
Hi,
we have a recurring issue on our prod environment:
```sh
/app/node_modules/apostrophe-workflow/lib/routes.js:1013
if (doc._url) {
^
TypeError: Cannot read property '_url' of undefined
at /app/node_modules/apostrophe-workflow/lib/routes.js:1013:14
```
We do not and cannot reproduce the issue, but after looking after the code, it seems it can be more robust, to handle the case where a doc is not found.
We added some error log, the case should not occurs and to have more information.
It would be nice to have it included in the next bug-fix release ;)
=> fix(link-to-locale): handle doc not found and log it

lib/callAll.js, lib/tasks.js
The `--live` option to `apostrophe-workflow:add-missing-locales` was not being passed on properly in all situations.
=> pass on all flags relating to the --live option properly

README.md, apostrophe-workflow, index.js, lib/callAll.js, lib/implementation.js, lib/modules/apostrophe-workflow-pages/index.js, lib/tasks.js, test/test3.js
When next you restart your app or run a command line task, Apostrophe detects the configuration change and runs the relevant tasks. In addition, add-locale-prefixes was rewritten to provide more optimal performance and avoid unnecessary work, and add-locale-prefixes is now smart enough to remove a prefix if you decide a locale shouldn't have one anymore.
=> dgad-484: no more need to run add-missing-locales or add-locale-prefixes, Apostrophe just figures it out

README.md
The docs for this module are great! However, it feels like they have grown organically over time, and at this point they are long enough to make them somewhat hard to navigate. I think we could do even more to give the different sections a clearer order and better structure, but this PR is just a simple effort to add an index to the top of the docs to make it easier to navigate them. I gave the index a tree structure in different levels, which is why I also "downgraded" the level of some headings (eg. from an `h3` to an `h4`).
=> Documentation: added an index to the README, restructured headings a little bit

README.md, lib/modules/apostrophe-workflow-docs/lib/cursor.js, test/testApi.js
$or queries are considered a bad smell in MongoDB and are slow in some cases.
Surprisingly in the general case, in simple test code without the full complexity of the Apostrophe query, performance was similar with $in versus $or, and explain() revealed that MongoDB was able to reduce it to a single query with two sets of index bounds, same as $in.
However it is possible this optimization is defeated in more complex queries. And, I was also able to use a pure equality test or no test at all in cases where the type filter is in play. That is a significant win.
Test code for simple cases showing the results mentioned above:
```
(function() {
db.dropDatabase();
db.docs.ensureIndex({ size: 1, workflowLocale: 1 });
const docs = [];
const locales = [ 'en', 'en-draft', 'fr', 'fr-draft', 'de', …
```
=> eliminated $or queries from the workflow module

lib/api.js, lib/routes.js, public/js/user.js
This addresses https://github.com/apostrophecms/apostrophe/issues/1641.
When an editor trashes a document, that only affects the draft version of that document. From a developer standpoint, this makes sense, since the `trash` property is just another property on the doc in the database. For the editor however, the document has effectively disappeared from the site now, and it's common for them not to be aware of the fact that they will need to find the document in the piece modal and manually commit it from there for it to actually be removed from the live site.
This commit changes that so that apostrophe-workflow by default looks up docs where the draft version has been trashed and the live version has not when editors commit a document. This makes it easy and obvious that trashed …
=> Show draft docs that have been trashed but not yet committed in commit modal by default

lib/middleware.js
Even though we intend to redirect visitors to the homepage of a locale in this particular location in the code, we didn't append a trailing slash to the locale prefix, which meant that visitors had to go through
an additional redirect.
Previously visitors would go from example.com -> example.com/uk -> example.com/uk/. With this change, they go directly from example.com -> example.com/uk/.
=> Add trailing slash to URL when redirecting visitors to locale homepage

lib/middleware.js
A simple solution to sync i18n with workflow module.
I know you have a branch yet to create a i18n bridge module to avoid copy locales in i18n module conf, but this is a simple working solution, if you configure both modules.
=> change i18n locale when changing locale in workflow

lib/routes.js
As discussed in #225. This makes it so that when user agents request a document from the link-to-locale route that doesn't exist, we no longer log an error. Instead, we redirect them to the slug they requested on the locale they requested – where they will see a regular 404 page.
=> Remove noisy link-to-locale 404 console error

lib/implementation.js
The 2.16.0 release included the new submittedModal option, but when that option is set to `false`, it simply moves the "Submitted" admin bar button out of the "Workflow" dropdown into the main admin bar. This change makes it so that the Submitted button is removed entirely from the admin bar when that option is set to `false`
=> Fix issues with disabling submittedModal

index.js, lib/api.js, lib/callAll.js, lib/implementation.js, lib/routes.js, test/test3.js, test/testReplicateFalse.js, views/locale-unavailable-modal.html
If the `replicateAcrossLocales` option of `apostrophe-workflow` is explicitly set to `false`, we do not replicate every document to every locale. Instead, we replicate only between the draft and live locales.
If the user wishes the document to exist in an additional locale, they can make it so by using any of the following functionality:
* "Export" (usually after commit).
* "Force Export".
* Using the locale switcher built into the editing interface to pick a locale that is currently "crossed out."
In this third case, a modal prompt appears asking if they want to create the document in the new locale. This is is the same exact interface we already use for similar edge cases, such as the document currently being in the trash in the other locale.
If the document is a page, and its parent …
=> 239 option to avoid replication

lib/tasks.js, test/testDereplicate.js
The option, which we published last week, prevents Apostrophe Workflow from copying every document to every locale automatically at creation time. The problem is that for those who are already using Workflow, there are already tons of documents that are "only really meant for one locale" but have been replicated already.
This task cleans up that situation. It is not a migration because it makes a subjective call, although it is perfect for most people migrating to this option. Edge cases like "I really truly want this to exist in other locales even though it's trash in all but one and I would be cheesed about having to export it later" are rare, we just need users to know that's what they are opting into.
The algorithm is this:
"If a document is trash in all locales but one, remove it …
=> apostrophe-workflow:dereplicate task, for migration to `replicateAcrossLocales: false`

lib/implementation.js
exists before other pages get replicated
=> when replicating parked pages we must go top down to ensure home page has already replicated, etc.

lib/modules/apostrophe-workflow-pieces/public/js/manager-modal.js
`exportAfterCommit` option is checked after commiting a piece but not when doing a batch commit.
=> Check 'exportAfterCommit' after batchCommit.

lib/callAll.js, lib/routes.js, views/menu.html
_Description_: Apostrophe currently has two workflow modes to view the docs
- Draft
- Live
The Permission model we(in our organisation) follow does't allow everybody to commit the changes to live mode. Only a few people has access to commit the pages while the others only has access to edit the content of the page. The following scenario explains the issue we are facing
- Lets say a user has edit access (lets call him **user 1**). He has edited the page but he has not viewed or cannot see how the page is going to look in live mode without all the "apos-ui" editor controls, without explicitly committing the page.
- This means a user with appropriate permissions (**user 2**) has to commit the page, every time
**user 1** wishes to see the widget or template he's working without "apos-ui" …
=> Add preview mode for users

lib/helpers.js, lib/modules/apostrophe-workflow-modified-documents/index.js, lib/modules/apostrophe-workflow-modified-documents/views/manageListPage.html, lib/routes.js
In #254 it was pointed out that the "manage workflow" modal can actually lead to a crash when an inappropriate user tries to use the "commit" buttons that should not be there, in their case.
Also the test for whether that modal is accessible at all needed a rethink for permissions.
In general workflow has thorough permissions support but this recently added modal, created in an era when some of our enterprise clients use permissions surprisingly little, had some loose ends.
=> fixed permissions issues around the "manage workflow" modal

lib/api.js, lib/helpers.js, lib/modules/apostrophe-workflow-modified-documents/index.js, lib/modules/apostrophe-workflow-modified-documents/views/manageListPage.html, lib/routes.js
Fix for #256:
* A mere editor (someone who can edit but not commit) can now properly see the "submit" button after they make the change.
* In addition, they will only see documents they can actually edit in the "Submitted" modal. That modal is not commonly used now that the "Manage Workflow" view is available, but it should still be appropriately robust in this area.
=> 256 allow mere editors to see submit button

README.md
The documentation described that creating the `admin` group on the command line would be possible in the future; this has been implemented by now, updating documentation.
=> Describing how to create admin user/group on CLI

lib/implementation.js, lib/middleware.js, test/test2-disable-anon-session.js, test/test2.js
If defaultLocaleByHostname states that the locale should be set, that should be a firm signal that always sets req.locale (after first checking for even better signals like hostname-plus-prefix), not a weak signal that waits for the guessLocale mechanism that only comes in if req.locale is completely empty.
Otherwise a preexisting default req.locale, as seen on DGAD, breaks this mechanism.
=> Default hostname is clear signal

CHANGELOG.md, lib/api.js, package.json
Currently the algorithm for applying a previous commit as a patch to another locale sweeps up all sub-properties of the document with an _id and treats them like widgets or array elements, seeking a match in the destination locale to apply the patch to, etc.
That's good for those but not great for attachment properties which have an _id but are part of the doc itself and should be handled by the patch algorithm that handles simple properties like `slug`. Exempt attachment properties from this step of the algorithm.
Needed for apostrophe-favicons 3.x, and also for allowing replacement of images in the media library to be exported properly across locales.
=> when an attachment property changes it should be possible to export it

lib/implementation.js, lib/middleware.js
Adds an option `defaultMode` to apostrophe-workflow to define which mode it should pick when the user has just logged in. (see https://github.com/apostrophecms/apostrophe-workflow/issues/174)
- `options.defaultMode` can be any of `live`, `draft` or `preview`
- if `options.defaultMode` is not set, or set to any other value, `draft` will be used (no warning raised)
=> Make default workflow mode configurable

CHANGELOG.md, lib/api.js, lib/modules/apostrophe-workflow-pages/index.js, package.json
With workflow, when we commit a page move, the slug is updated using the draft one in workflow. Then it calls the `self.move` method of `apostrophe-pages`, inside the slug is updated again.
This behavior produces bad slugs by duplicating it, example `/block-page/sub-page` becomes `/block-page/block-page/sub-page`.
=> Slug updated twice

CHANGELOG.md, README.md, index.js, lib/api.js, lib/implementation.js, lib/modules/apostrophe-workflow-pages/index.js, lib/tasks.js
Passing a flag in the workflow configuration allows to auto commit only moves automatically.
Linked to this PR: https://github.com/apostrophecms/apostrophe/pull/3000
=> Moves draft and live pages at the same time

CHANGELOG.md, lib/tasks.js
Avoiding duplicate key errors from mongoDB during migration.
If duplicate path error, we mark the pages with the duplicate path if they have not been updated already (because their path will be updated with the draft version later).
=> Fix duplicate key error in sync page

CHANGELOG.md, lib/modules/apostrophe-workflow-pages/index.js
Issue when creating a website on an Assembly project using the `apostrophe-headless` module. 
The `modulesReady` callback was missing so the website creation was loading infinitely
=> Fix assembly bug when creating site
